### ISSUE TITLE
Add option for X axis to show wall-clock-time

### ISSUE THREAD

**Issue by giltene** [HdrHistogram/HistogramLogAnalyzer#7]
The ability for the X-axis to display wall clock time (as opposed to time since start of log) would be very helpful, especially when triaging issues externally flagged by time.

See the in-development -usedatex option in the Zing GCLogAnalyzer for example of how this might work.

**Comment by dimitryc** [comment]
Commit: https://github.com/HdrHistogram/HistogramLogAnalyzer/commit/336a1977f97dc8dd9faea20af424c3c02f8e51f0

Current UI changes:
 - added new menu item "View" -> "Show date/time" that toggles between wall-clock time and time since start of log
 - default date format of new chart is "HH:mm"
 - tool attempts to automatically detect timezone based on info from log and uses it in new charts (abbreviation of timezone in use appears as chart label)
 - added new menu item "File" -> "Configure Date/Time" that opens new panel and allows to override default settings (date/time format, timezone)
